---

env:
  browser: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  array-bracket-newline: [error, consistent]
  array-bracket-spacing: [error, always]
  array-element-newline: [error, consistent]
  block-spacing: [error, always]
  brace-style: [error, stroustrup]
  capitalized-comments: [error, always]
  class-methods-use-this: [error]
  comma-dangle: [error, always-multiline]
  comma-spacing: [error, {before: false, after: true}]
  computed-property-spacing: [error, never]
  consistent-return: [error]
  curly: [error, all]
  dot-location: [error, object]
  eol-last: [error, always]
  eqeqeq: [error, always]
  func-call-spacing: [error, never]
  function-call-argument-newline: [error, consistent]
  function-paren-newline: [error, consistent]
  indent:
    - error
    - 2
    - ArrayExpression: first
      CallExpression: {arguments: first}
      FunctionDeclaration: {parameters: first}
      FunctionExpression: {parameters: first}
      ImportDeclaration: first
      ObjectExpression: first
  key-spacing: [error, {beforeColon: false, afterColon: true}]
  linebreak-style: [error, unix]
  lines-between-class-members: [error, always]
  max-len: [error, {code: 80}]
  no-tabs: [error, {allowIndentationTabs: false}]
  no-trailing-spaces: [error]
  no-var: [error]
  object-curly-spacing: [error, always]
  prefer-object-spread: [error]
  prefer-rest-params: [error]
  quotes: [error, single]
  semi: [error, always]
  sort-imports: [error, {allowSeparatedGroups: true}]
  spaced-comment: [error, always]
